### ISSUE TITLE
Could it normalize microarray data to RNAseq data?

### ISSUE THREAD

**Issue by wanhui5867** [greenelab/TDM#8]
Could we use it to normalise microarray data to make them comparable to RNAseq data?

**Comment by cgreene** [comment]
Hi @wanhui5867 - we thought about this question while doing the work. However, we did not evaluate performance in this context. Our thinking at the time was that we expected compression in the array but not RNA-seq data because saturation at the high end would be less of a problem with count-based data. Some continued investigations are happening over on https://github.com/greenelab/RNAseq_titration_results at the moment. I don't think they necessarily directly answer your question, but they are the natural extension of this work.
